basic_settings:
  site_title: Chimichurri Code
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/one-line.svg
  logo_width: 200

menu_settings:
  menu_items:
#    - title: 'Projects'
#      url: '/'
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about'
    - title: 'Escuchame'
      url: '/listen'

footer_settings:
  footer_tagline: From üá¶üá∑ with ‚ô•Ô∏è and üíª.

hero_settings:
  overlay_opacity: 0.8

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/npatarino'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: 'https://youtube.com/chimichurricode'
  spotify_url: 'https://open.spotify.com/show/0fCxnCusjI9frMmdANEENl'
  google_url: 'https://podcasts.google.com/feed.xml/aHR0cHM6Ly93d3cuc3ByZWFrZXIuY29tL3Nob3cvNDY3MzQ3NS9lcGlzb2Rlcy9mZWVk'
  apple_url: 'https://podcasts.apple.com/es/podcast/chimichurri-code/id1540996983'
  deezer_url: 'https://www.deezer.com/en/show/1989502'
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  bandcamp_url: ''
  linkedin_url: ''

podcast_settings:
  microphone-alt_url: 'https://www.ivoox.com/podcast-chimichurri-code_sq_f11110415_1.html'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#FE8131'
  border_color: '#dddddd'
  hero_background_color: '#132930'
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700&display=swap" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 35
    medium_size: 45
    large_size: 60
    weight: 700
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 20
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""